image: 
  file: Fruitful3DNative.Dockerfile


#additionalRepositories:
#  - url: https://github.com/JesseRigon/FreeCAD
#    checkoutLocation: FreeCAD

workspaceLocation: FreeCAD-GP/main.code-workspace

