image: 
  file: Fruitful3DNative.Dockerfile

ports:
  - port: 6080
    visibility: private
    onOpen: open-browser

  - port: 1593
    onOpen: ignore

  - port: 5900
    onOpen: ignore


additionalRepositories:
  - url: https://github.com/JesseRigon/FreeCAD
    checkoutLocation: FreeCAD

workspaceLocation: FreeCAD-GP/main.code-workspace

