image: gitpod/workspace-full-vnc

tasks:
  - name: update
    init: |
      sudo apt-get update
      sudo apt-get upgrade -y
      sudo apt-get autoremove
      sudo apt-get autoclean
      gp sync-done update
     
  - name: Conda
    init: |
      gp sync-await update
      wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh
      bash ~/miniconda.sh -b -p ~/miniconda
      eval "$(~/miniconda/bin/conda shell.bash hook)"
      conda init
    
#  - name: FreeCAD
#    init: |

    

ports:
  - port: 6080
    visibility: public
    onOpen: open-browser

  - port: 1593
    onOpen: ignore

  - port: 5900
    onOpen: ignore

github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true

additionalRepositories:
  - url: https://github.com/JesseRigon/FreeCAD
    checkoutLocation: FreeCAD

workspaceLocation: FreeCAD-GP/main.code-workspace

