image: gitpod/workspace-full-vnc

tasks:
  - name: Update
    before: |
      sudo apt-get update
      sudo apt-get upgrade -y
      sudo apt-get autoremove
      sudo apt-get autoclean
      gp sync-done Update
      exit
     
  - name: FreecadReqs
    before: |
      gp sync-await Update
      sudo apt-get install -y freecad
      sudo apt install -y cmake cmake-gui libboost-date-time-dev libboost-dev libboost-filesystem-dev libboost-graph-dev libboost-iostreams-dev libboost-program-options-dev libboost-python-dev libboost-regex-dev libboost-serialization-dev libboost-thread-dev libcoin-dev libeigen3-dev libgts-bin libgts-dev libkdtree++-dev libmedc-dev libocct-data-exchange-dev libocct-ocaf-dev libocct-visualization-dev libopencv-dev libproj-dev libpyside2-dev libqt5opengl5-dev libqt5svg5-dev qtwebengine5-dev libqt5x11extras5-dev libqt5xmlpatterns5-dev libshiboken2-dev libspnav-dev libvtk7-dev libx11-dev libxerces-c-dev libzipios++-dev occt-draw pyside2-tools python3-dev python3-matplotlib python3-packaging python3-pivy python3-ply python3-pyside2.qtcore python3-pyside2.qtgui python3-pyside2.qtsvg python3-pyside2.qtwidgets python3-pyside2.qtnetwork python3-pyside2.qtwebengine python3-pyside2.qtwebenginecore python3-pyside2.qtwebenginewidgets python3-pyside2.qtwebchannel python3-markdown python3-git qtbase5-dev qttools5-dev swig
      gp sync-done FreecadReqs

  - name: FreecadBuild
    init: |
      gp sync-await FreecadReqs
      cd ../
      mkdir Builds
      cd Builds
      cmake ../FreeCAD -DBUILD_QT5=ON -DPYTHON_EXECUTABLE=/usr/bin/python3
      make

ports:
  - port: 6080
    visibility: public
    onOpen: open-browser

  - port: 1593
    onOpen: ignore

  - port: 5900
    onOpen: ignore

github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true

additionalRepositories:
  - url: https://github.com/JesseRigon/FreeCAD
    checkoutLocation: FreeCAD

workspaceLocation: FreeCAD-GP/main.code-workspace

