version: "3.2"
services:
  freecad_local:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - FREECAD_DOCKER_IMAGE
        - SOURCE_FOLDER
        - BUILD_FOLDER
        - FILES_FOLDER
    working_dir: /root

  freecad_container_service:
    container_name: freecad_container_service
    build: .
    volumes:
      - type: volume
        source: source_folder
        target: /mnt/source
      - type: volume
        source: build_folder
        target: /mnt/build
      - type: bind
        source: "./${FILES_FOLDER}"
        target: /mnt/files
      - type: bind
        source: /tmp/.X11-unix
        target: /tmp/.X11-unix
        read_only: true
    depends_on:
      - freecad_local
    working_dir: /root
    entrypoint: /mnt/build/bin/FreeCAD --version

volumes:
  source_folder:
    external: true
    name: ${SOURCE_FOLDER}
  build_folder:
    external: true
    name: ${BUILD_FOLDER}