ARG FREECAD_DOCKER_IMAGE
FROM ${FREECAD_DOCKER_IMAGE}

# Copy the source code.
ARG SOURCE_FOLDER
COPY ${SOURCE_FOLDER} /mnt/source

# FreeCAD Display Routing
ENV DISPLAY=:0
ENV QT_X11_NO_MITSHM=1
ENV LIBGL_ALWAYS_INDIRECT=1