version: "3.2"
services:
  FreeCAD:
    container_name: FreeCAD${TAG_NUMBER}
    image: ${FREECAD_DOCKER_IMAGE}
    volumes:
      - type: volume
        source: source_folder
        target: /mnt/source
      - type: volume
        source: build_folder
        target: /mnt/build
      - type: volume
        source: files_folder
        target: /mnt/files
      - type: bind
        source: /tmp/.X11-unix
        target: /tmp/.X11-unix
        read_only: true
    working_dir: /root
    entrypoint: /mnt/build/bin/FreeCAD

volumes:
  source_folder:
    external: true
    name: ${SOURCE_FOLDER}
  build_folder:
    external: true
    name: ${BUILD_FOLDER}
  files_folder:
    external: true
    name: ${FILES_FOLDER}